language: node_js
node_js:
- stable
branches:
  only:
  - dev
jobs:
  include:
  - stage: test
    script: npm test
  - stage: building
    script:
    - bash scripts/deploy.sh
    before_install: bash scripts/install.sh
    env:
    - REMOTE_PATH=project/
    - REMOTE_USER=travisci
    - REMOTE_HOST=165.22.77.10
    - REMOTE_PORT=22
